"""Perturbative DeePHF energy and strict molecular analytic gradients."""

from .adjoint import (
    AdjointDiagnostics,
    AdjointError,
    AdjointResult,
    ScalarAdjointProblem,
    scalar_operator_fingerprint,
    solve_scalar_adjoint,
)
from .ase import DeePHFCalculator

from .capabilities import (
    DeePHFCapabilityError,
    validate_force_model,
    validate_model,
    validate_model_output,
)
from .gradient import (
    RHFDeePHFGradients,
    RKSDeePHFGradients,
    UHFDeePHFGradients,
    UKSDeePHFGradients,
)
from .gpu_method import (
    GPUDeePHF,
    GPUDeePHFGradients,
    GPURKSDeePHF,
    GPUUHFDeePHF,
    GPUUKSDeePHF,
)
from .gpu_scanner import (
    GPUDeePHFGradientScanner,
    GPUDeePHFScannerError,
    GPUUHFDeePHFGradientScanner,
)
from .force_data import (
    RHFForceDataError,
    RHFForceFrame,
    generate_rhf_force_frame,
    write_rhf_force_dataset,
)
from .method import DeePHF
from .pyscf_rhf import (
    RHFAdjoint,
    RHFAdjointAdapter,
    RHFAdjointDiagnostics,
    RHFAdjointError,
    RHFResponse,
    RHFResponseAdapter,
    RHFBlockedResponseSummary,
    RHFResponseDiagnostics,
    RHFResponseError,
    RHFRootSnapshot,
    RHFScannerReferenceError,
    RHFScannerReferenceFactory,
    validate_reference,
)
from .scanner import RHFDeePHFGradientScanner, RHFDeePHFScannerError
from .contracts import RootContinuityError
from .unrestricted_method import UHFDeePHF, UKSDeePHF
from .pyscf_uhf import (
    UHFAdjoint,
    UHFAdjointAdapter,
    UHFAdjointDiagnostics,
    UHFAdjointError,
    UHFResponse,
    UHFResponseAdapter,
    UHFResponseDiagnostics,
    UHFResponseError,
    validate_uhf_reference,
)
from .rks_method import RKSDeePHF
from .pyscf_rks import (
    RKSAdjoint,
    RKSAdjointAdapter,
    RKSAdjointDiagnostics,
    RKSAdjointError,
    RKSFunctionalProvenance,
    RKSGridProvenance,
    RKSResponse,
    RKSResponseAdapter,
    RKSResponseDiagnostics,
    RKSResponseError,
    validate_rks_reference,
)
from .pyscf_uks import (
    UKSAdjoint,
    UKSAdjointAdapter,
    UKSAdjointDiagnostics,
    UKSAdjointError,
    UKSResponse,
    UKSResponseAdapter,
    UKSResponseDiagnostics,
    UKSResponseError,
    validate_uks_reference,
)
from .zvector import (
    RHFDeePHFZVectorGradients,
    RKSDeePHFZVectorGradients,
    UHFDeePHFZVectorGradients,
    UKSDeePHFZVectorGradients,
)
from .workflow import build_reference, evaluate_molecule, make_deephf

__all__ = [
    "DeePHF",
    "DeePHFCalculator",
    "DeePHFCapabilityError",
    "GPUDeePHF",
    "GPUDeePHFGradients",
    "GPUDeePHFGradientScanner",
    "GPUDeePHFScannerError",
    "GPURKSDeePHF",
    "GPUUHFDeePHF",
    "GPUUHFDeePHFGradientScanner",
    "GPUUKSDeePHF",
    "AdjointDiagnostics",
    "AdjointError",
    "AdjointResult",
    "RHFDeePHFGradients",
    "RHFDeePHFGradientScanner",
    "RHFDeePHFScannerError",
    "RHFDeePHFZVectorGradients",
    "RHFForceDataError",
    "RHFForceFrame",
    "RHFAdjoint",
    "RHFAdjointAdapter",
    "RHFAdjointDiagnostics",
    "RHFAdjointError",
    "RHFResponse",
    "RHFResponseAdapter",
    "RHFBlockedResponseSummary",
    "RHFResponseDiagnostics",
    "RHFResponseError",
    "RHFRootSnapshot",
    "RHFScannerReferenceError",
    "RHFScannerReferenceFactory",
    "RootContinuityError",
    "RKSDeePHF",
    "RKSDeePHFGradients",
    "RKSDeePHFZVectorGradients",
    "RKSAdjoint",
    "RKSAdjointAdapter",
    "RKSAdjointDiagnostics",
    "RKSAdjointError",
    "RKSFunctionalProvenance",
    "RKSGridProvenance",
    "RKSResponse",
    "RKSResponseAdapter",
    "RKSResponseDiagnostics",
    "RKSResponseError",
    "ScalarAdjointProblem",
    "UHFDeePHF",
    "UHFDeePHFGradients",
    "UHFDeePHFZVectorGradients",
    "UHFAdjoint",
    "UHFAdjointAdapter",
    "UHFAdjointDiagnostics",
    "UHFAdjointError",
    "UHFResponse",
    "UHFResponseAdapter",
    "UHFResponseDiagnostics",
    "UHFResponseError",
    "UKSDeePHF",
    "UKSDeePHFGradients",
    "UKSDeePHFZVectorGradients",
    "UKSAdjoint",
    "UKSAdjointAdapter",
    "UKSAdjointDiagnostics",
    "UKSAdjointError",
    "UKSResponse",
    "UKSResponseAdapter",
    "UKSResponseDiagnostics",
    "UKSResponseError",
    "generate_rhf_force_frame",
    "solve_scalar_adjoint",
    "scalar_operator_fingerprint",
    "validate_model",
    "validate_force_model",
    "validate_model_output",
    "validate_reference",
    "validate_rks_reference",
    "validate_uhf_reference",
    "validate_uks_reference",
    "write_rhf_force_dataset",
    "build_reference",
    "evaluate_molecule",
    "make_deephf",
]
