"""Perturbative DeePHF energy method for a strict native RKS reference."""

import numpy as np

from .capabilities import science_state_transaction
from .method import (
    DeePHF,
    _DIRECT_RESPONSE_OPTIONS,
    _validated_backend_options,
)
from .pyscf_dft_provenance import RKSResponse, RKSResponseError
from .pyscf_rks_adjoint import RKSAdjointAdapter
from .pyscf_rks_reference import (
    rks_reference_fingerprint,
    validate_rks_reference,
)
from .pyscf_rks_response import RKSResponseAdapter


_RKS_ZVECTOR_OPTIONS = frozenset(
    {
        "residual_tolerance",
        "invariant_tolerance",
        "orbital_gap_tolerance",
        "objective_symmetry_tolerance",
        "max_cycle",
        "krylov_restart",
    }
)


class RKSDeePHF(DeePHF):
    """Evaluate a perturbative correction around one strict RKS reference."""

    _adjoint_adapter_type = RKSAdjointAdapter
    _response_adapter_type = RKSResponseAdapter
    _zvector_options = _RKS_ZVECTOR_OPTIONS

    @staticmethod
    def _validate_reference_object(reference):
        return validate_rks_reference(reference)

    @staticmethod
    def _reference_state_fingerprint(reference) -> str:
        return rks_reference_fingerprint(reference)

    def __init__(
        self,
        reference,
        model,
        projector_basis=None,
        device="cpu",
        response_options=None,
        adjoint_options=None,
    ):
        super().__init__(
            reference,
            model,
            projector_basis=projector_basis,
            device=device,
            response_options=response_options,
            adjoint_options=adjoint_options,
        )

    def _validate_response(self, response: RKSResponse) -> RKSResponse:
        """Return a response produced by this exact RKS method."""
        self._assert_science_state("RKS response consumption")
        self._validate_reference_object(self.reference)
        if type(response) is not RKSResponse:
            raise RKSResponseError("the supplied RKS response has an invalid type")
        if not self._is_sealed_response(response):
            raise RKSResponseError(
                "the supplied RKS response was not produced by this RKS DeePHF method"
            )
        return response

    def first_order_density(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return the complete numerical AO density derivative dP/dR."""
        if response is not None and response_options:
            raise ValueError("response and response_options are mutually exclusive")
        if response is None:
            response = self.response(**response_options)
        return self._validate_response(response).density_response

    @science_state_transaction
    def dq_dR_response(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return the descriptor derivative generated by the RKS response."""
        density_response = self.first_order_density(
            response=response,
            **response_options,
        )
        result = np.einsum(
            "apij,bxij->bxap",
            self.dq_dP(),
            density_response,
        )
        if not np.isfinite(result).all():
            raise RKSResponseError(
                "the RKS descriptor response is nonfinite"
            )
        return result

    @science_state_transaction
    def dq_dR_relaxed(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return complete relaxed dq/dR for the RKS reference."""
        if response is None:
            response = self.response(**response_options)
            response_options = {}
        else:
            self.validate_force_compatibility()
        return self.dq_dR_explicit() + self.dq_dR_response(
            response=response,
            **response_options,
        )

    def nuc_grad_method(self, *, backend="direct", retain_details=True, **backend_options):
        """Build one explicitly selected strict RKS gradient backend."""
        if type(backend) is not str or backend not in {"direct", "zvector"}:
            raise ValueError(
                "RKS gradient backend must be 'direct' or 'zvector'"
            )
        if backend == "direct":
            _validated_backend_options(
                self.response_options,
                backend_options,
                _DIRECT_RESPONSE_OPTIONS,
                backend,
            )
            from .rks_gradient import RKSDeePHFGradients

            return RKSDeePHFGradients(
                self,
                response_options=backend_options,
                retain_details=retain_details,
            )
        _validated_backend_options(
            self.adjoint_options,
            backend_options,
            _RKS_ZVECTOR_OPTIONS,
            backend,
        )
        from .rks_zvector import RKSDeePHFZVectorGradients

        return RKSDeePHFZVectorGradients(
            self,
            adjoint_options=backend_options,
            retain_details=retain_details,
        )


__all__ = ["RKSDeePHF"]
