"""Perturbative DeePHF energy method for a strict native RKS reference."""

from collections.abc import Mapping

import numpy as np

from .capabilities import DeePHFCapabilityError
from .method import DeePHF, _DIRECT_RESPONSE_OPTIONS, _validated_backend_options
from .pyscf_rks import (
    RKSResponse,
    RKSResponseAdapter,
    RKSResponseDiagnostics,
    RKSResponseError,
    rks_reference_fingerprint,
    validate_rks_reference,
)


class RKSDeePHF(DeePHF):
    """Evaluate a perturbative correction around one strict RKS reference."""

    @staticmethod
    def _validate_reference_object(reference):
        return validate_rks_reference(reference)

    @staticmethod
    def _reference_state_fingerprint(reference) -> str:
        return rks_reference_fingerprint(reference)

    def __init__(
        self,
        reference,
        model,
        projector_basis=None,
        device="cpu",
        response_options=None,
        adjoint_options=None,
    ):
        if adjoint_options is not None:
            if not isinstance(adjoint_options, Mapping):
                raise TypeError("adjoint_options must be a mapping")
            if adjoint_options:
                raise DeePHFCapabilityError(
                    "RKS DeePHF does not provide an adjoint backend"
                )
        super().__init__(
            reference,
            model,
            projector_basis=projector_basis,
            device=device,
            response_options=response_options,
            adjoint_options={},
        )

    def response(self, **response_options) -> RKSResponse:
        """Solve the audited complete finite-grid RKS density response."""
        self._trusted_response = None
        self._trusted_response_integrity = None
        self.validate_force_compatibility()
        options = _validated_backend_options(
            self.response_options,
            response_options,
            _DIRECT_RESPONSE_OPTIONS,
            "direct",
        )
        response = RKSResponseAdapter(self.reference, **options).solve()
        self._trusted_response = response
        self._trusted_response_integrity = response.integrity_fingerprint
        return response

    @staticmethod
    def _response_adapter_options(diagnostics: RKSResponseDiagnostics) -> dict:
        return {
            "cphf_tolerance": diagnostics.cphf_tolerance,
            "residual_tolerance": diagnostics.residual_tolerance,
            "invariant_tolerance": diagnostics.invariant_tolerance,
            "orbital_gap_tolerance": diagnostics.orbital_gap_tolerance,
            "max_cycle": diagnostics.max_cycle,
            "max_refinement_cycles": diagnostics.max_refinement_cycles,
            "level_shift": diagnostics.level_shift,
            "operator_stability_tolerance": (
                diagnostics.operator_stability_tolerance
            ),
            "operator_condition_tolerance": (
                diagnostics.operator_condition_tolerance
            ),
            "operator_symmetry_tolerance": (
                diagnostics.operator_symmetry_tolerance
            ),
            "operator_dimension_limit": diagnostics.operator_dimension_limit,
        }

    def _validate_response(self, response: RKSResponse) -> RKSResponse:
        """Rebuild and audit one supplied finite-grid RKS response."""
        self._validate_reference_object(self.reference)
        if type(response) is not RKSResponse:
            raise RKSResponseError("the supplied RKS response has an invalid type")
        if type(response.diagnostics) is not RKSResponseDiagnostics:
            raise RKSResponseError(
                "the supplied RKS response diagnostics have an invalid type"
            )
        adapter = RKSResponseAdapter(
            self.reference,
            **self._response_adapter_options(response.diagnostics),
        )
        adapter.audit_response_equations(response)
        return response

    def first_order_density(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return the complete numerical AO density derivative dP/dR."""
        if response is not None and response_options:
            raise ValueError("response and response_options are mutually exclusive")
        if response is None:
            response = self.response(**response_options)
        return self._validate_response(response).density_response

    def dq_dR_response(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return the descriptor derivative generated by the RKS response."""
        self.validate_force_compatibility()
        density_response = self.first_order_density(
            response=response,
            **response_options,
        )
        result = np.einsum(
            "apij,bxij->bxap",
            self.dq_dP(),
            density_response,
        )
        if not np.isfinite(result).all():
            raise RKSResponseError(
                "the RKS descriptor response is nonfinite"
            )
        return result

    def dq_dR_relaxed(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return complete relaxed dq/dR for the RKS reference."""
        if response is None:
            response = self.response(**response_options)
            response_options = {}
        return self.dq_dR_explicit() + self.dq_dR_response(
            response=response,
            **response_options,
        )

    def adjoint(self, **adjoint_options):
        """Reject unavailable RKS adjoint inference."""
        raise DeePHFCapabilityError(
            "RKS DeePHF does not provide an adjoint backend"
        )

    def _zvector_inputs(self, adjoint_options):
        raise DeePHFCapabilityError(
            "RKS DeePHF does not provide a Z-vector backend"
        )

    def nuc_grad_method(self, *, backend="direct", **backend_options):
        """Build the strict RKS direct analytic-gradient backend."""
        if type(backend) is not str or backend != "direct":
            raise DeePHFCapabilityError(
                "the RKS DeePHF gradient backend must be 'direct'"
            )
        _validated_backend_options(
            self.response_options,
            backend_options,
            _DIRECT_RESPONSE_OPTIONS,
            backend,
        )
        from .rks_gradient import RKSDeePHFGradients

        return RKSDeePHFGradients(
            self,
            response_options=backend_options,
        )


__all__ = ["RKSDeePHF"]
