"""Perturbative DeePHF energy method for a strict native RKS reference."""

import numpy as np

from .capabilities import science_state_transaction
from .method import (
    DeePHF,
    _DIRECT_RESPONSE_OPTIONS,
    _immutable_array,
    _validated_backend_options,
)
from .pyscf_rks import (
    RKSAdjoint,
    RKSAdjointAdapter,
    RKSResponse,
    RKSResponseAdapter,
    RKSResponseError,
    rks_reference_fingerprint,
    validate_rks_reference,
)


_RKS_ZVECTOR_OPTIONS = frozenset(
    {
        "residual_tolerance",
        "invariant_tolerance",
        "orbital_gap_tolerance",
        "objective_symmetry_tolerance",
        "max_cycle",
        "krylov_restart",
    }
)


class RKSDeePHF(DeePHF):
    """Evaluate a perturbative correction around one strict RKS reference."""

    @staticmethod
    def _validate_reference_object(reference):
        return validate_rks_reference(reference)

    @staticmethod
    def _reference_state_fingerprint(reference) -> str:
        return rks_reference_fingerprint(reference)

    def __init__(
        self,
        reference,
        model,
        projector_basis=None,
        device="cpu",
        response_options=None,
        adjoint_options=None,
    ):
        super().__init__(
            reference,
            model,
            projector_basis=projector_basis,
            device=device,
            response_options=response_options,
            adjoint_options=adjoint_options,
        )

    @science_state_transaction
    def response(self, **response_options) -> RKSResponse:
        """Solve the audited complete finite-grid RKS density response."""
        self.validate_force_compatibility()
        return self._solve_response(response_options)

    def _solve_response(
        self,
        response_options,
        atom_indices=None,
        result_mode="response",
    ):
        """Solve one response after the caller has validated descriptor semantics."""
        options = _validated_backend_options(
            self.response_options,
            response_options,
            _DIRECT_RESPONSE_OPTIONS,
            "direct",
        )
        adapter = RKSResponseAdapter(self.reference, **options)
        if result_mode == "gradient":
            return adapter._solve_for_gradient(atom_indices=atom_indices)
        if result_mode == "partitions":
            response, density_partitions = adapter._solve_with_density_partitions(
                atom_indices=atom_indices
            )
        else:
            response = adapter.solve(atom_indices=atom_indices)
        self._seal_response(response)
        return (
            (response, density_partitions)
            if result_mode == "partitions"
            else response
        )

    def _validate_response(self, response: RKSResponse) -> RKSResponse:
        """Return a response produced by this exact RKS method."""
        self._assert_science_state("RKS response consumption")
        self._validate_reference_object(self.reference)
        if type(response) is not RKSResponse:
            raise RKSResponseError("the supplied RKS response has an invalid type")
        if not self._is_sealed_response(response):
            raise RKSResponseError(
                "the supplied RKS response was not produced by this RKS DeePHF method"
            )
        return response

    def first_order_density(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return the complete numerical AO density derivative dP/dR."""
        if response is not None and response_options:
            raise ValueError("response and response_options are mutually exclusive")
        if response is None:
            response = self.response(**response_options)
        return self._validate_response(response).density_response

    @science_state_transaction
    def dq_dR_response(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return the descriptor derivative generated by the RKS response."""
        density_response = self.first_order_density(
            response=response,
            **response_options,
        )
        result = np.einsum(
            "apij,bxij->bxap",
            self.dq_dP(),
            density_response,
        )
        if not np.isfinite(result).all():
            raise RKSResponseError(
                "the RKS descriptor response is nonfinite"
            )
        return result

    @science_state_transaction
    def dq_dR_relaxed(
        self,
        response: RKSResponse | None = None,
        **response_options,
    ) -> np.ndarray:
        """Return complete relaxed dq/dR for the RKS reference."""
        if response is None:
            response = self.response(**response_options)
            response_options = {}
        else:
            self.validate_force_compatibility()
        return self.dq_dR_explicit() + self.dq_dR_response(
            response=response,
            **response_options,
        )

    @science_state_transaction
    def adjoint(self, **adjoint_options) -> RKSAdjoint:
        """Solve one audited correction-specific RKS scalar adjoint."""
        return self._zvector_inputs(adjoint_options)[2]

    def _zvector_inputs(self, adjoint_options, atom_indices=None):
        """Build one RKS sensitivity and one scalar adjoint."""
        self._validate_reference_object(self.reference)
        descriptor_diagnostics, sensitivity = self._force_inputs()
        sensitivity = _immutable_array(sensitivity)
        options = _validated_backend_options(
            self.adjoint_options,
            adjoint_options,
            _RKS_ZVECTOR_OPTIONS,
            "zvector",
        )
        objective = self._correction_ao_potential(sensitivity)
        adjoint = RKSAdjointAdapter(self.reference, **options).solve(
            objective,
            atom_indices=atom_indices,
        )
        return descriptor_diagnostics, sensitivity, adjoint

    def nuc_grad_method(self, *, backend="direct", retain_details=True, **backend_options):
        """Build one explicitly selected strict RKS gradient backend."""
        if type(backend) is not str or backend not in {"direct", "zvector"}:
            raise ValueError(
                "RKS gradient backend must be 'direct' or 'zvector'"
            )
        if backend == "direct":
            _validated_backend_options(
                self.response_options,
                backend_options,
                _DIRECT_RESPONSE_OPTIONS,
                backend,
            )
            from .rks_gradient import RKSDeePHFGradients

            return RKSDeePHFGradients(
                self,
                response_options=backend_options,
                retain_details=retain_details,
            )
        _validated_backend_options(
            self.adjoint_options,
            backend_options,
            _RKS_ZVECTOR_OPTIONS,
            backend,
        )
        from .rks_zvector import RKSDeePHFZVectorGradients

        return RKSDeePHFZVectorGradients(
            self,
            adjoint_options=backend_options,
            retain_details=retain_details,
        )


__all__ = ["RKSDeePHF"]
